### ISSUE TITLE
Connexion Reset By Peer

### ISSUE THREAD

**Issue by ghost** [Fox2Code/UDK#1]
https://pastebin.com/vY2J6398
Voila la stack complette 

0x14

**Comment by Fox2Code** [comment]
Semm you are running UDK behind a firewall please sent more information about the current issue
In this case, try checking the firewall or your current DNS server.
If I am getting other reports I might implement DoH but without more information I can't do so much.

**Comment by ghost** [comment]
I'ts work ! my firewall  block your app XD
